# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!
env:
  PYTHONPATH: "./src"

tasks:
  run:
    cmds:
      - poetry run python ./src/comfybot.py -- -c local/comfybot.json
  lint:
    cmds:
      - poetry run ruff check src
  test:
    cmds:
      - poetry run pytest .
